print('====== DESAFIO 006 ======')
print()
print('Crie um algoritmo que leia um número e mostre o seu dobro, triplo e raiz quadrada.')
print()
n = int(input('Digite um número : '))
print('Dobro : {}'.format(n*2))
print('Triplo : {}'.format((n*3)))
print('Raiz Quadrada : {}'.format(n**0.5))
print()
print('Criado por : Marcelo Augusto')
