print('====== DESAFIO 010 ======')
print()
print('Crie um programa que leia quanto dinheiro uma pessoa tem na carteira e mostre quantos dólares ela pode comprar.')
print('Considere US$ 5,38 para cada R$ 1 real.')
print()
valor = float(input('Digite um valor em Real (R$) : '))
print('Você pode comprar US$ {:.2f} dólares .'.format(valor/5.38))
print()
print('Criado por : Marcelo Augusto')
