print('====== DESAFIO 004 ======')
print()
print('Faça um programa que leia algo pelo teclado e mostre na tela o seu tipo primitivo\ne todas as informações possíveis sobre ele.')
print()
a = input('Digite algo : ')
print()
print('00 . Qual o Tipo Primitivo ? ', type(a))
print('01 . É Numérico (Frações, Subscritos, etc) ? ', a.isnumeric())
print('02 . É algum Dígito (0 - 9) ? ', a.isdigit())
print('03 . São caracteres Decimais (0 - 9) ? ', a.isdecimal())
print('04 . É Alfabeto ? ', a.isalpha())
print('05 . É Alfanumérico (Letras e Números)  ? ', a.isalnum())
print('06 . É Espaço em Branco (Espaço, Tabulação, Nova Linha) ? ', a.isspace())
print('07 . São todos Minúsculos ? ', a.islower())
print('08 . São todos Maiúsculos ? ', a.isupper())
print('09 . É um Identificador Válido ? ', a.isidentifier())
print('10 . São caracteres Imprimíveis  (visíveis, como Letras, Números e Espaços) ? ', a.isprintable())
print('11 . Segue as regras de Capitalização de um Título ? ', a.istitle())
print('12 . Só tem Espaços ? ', a.isspace())
print()
print('Criado por : Marcelo Augusto')
