print('====== DESAFIO 002 ======')
print()
print('Se apresente.')
print()
nome = input ('Digite seu nome : ')
print('Seja bem-vindo(a) , {} !'.format(nome))
nome1 = input('Digite seu nome : ')
print('Seja bem-vindo(a) , {} !'.format(nome1))
print()
print('Criado por : Marcelo Augusto')
