print('====== DESAFIO 008 ======')
print()
print('Escreva um programa que leia um valor em metros e o exiba convertido em centímetros e milímetros.')
print()
metros = float(input('Digite um valor em metros : '))
print('Centímetros : ', '{}'.format(metros*100))
print('Milímetros : ', '{}'.format(metros*1000))
print()
print('Criado por : Marcelo Augusto')
